// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Logic.CMS.ResourceCatalog.HashEnums
{
    public enum HashParticles : uint
    {
        Blood0 = 1387543832u,
        BloodSplash = 373535561u,
        Hit0 = 1053977925u,
        ImpactLines = 2191773397u,
        MotionLines = 3814381622u,
        Poof = 2988167935u,
        Slash_LtoR = 1365824273u,
        Slash_RtoL = 667885407u,
        Slash_RtoL45 = 256171857u,
        SlashForward = 3502476599u,
        SmallPoof = 3186437583u,
    }
}
