// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Logic.CMS.ResourceCatalog.HashEnums
{
    public enum HashEnemies_Goblins : uint
    {
        Goblin = 477209154u,
    }
}
